// <auto-generated />
using System;
using DailyRhythms.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DailyRhythms.Migrations
{
    [DbContext(typeof(DailyRhythmsContext))]
    [Migration("20240114021646_Postgres date")]
    partial class Postgresdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DailyRhythms.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 14, 2, 16, 46, 418, DateTimeKind.Utc).AddTicks(2143),
                            Name = "Morning",
                            UpdatedAt = new DateTime(2024, 1, 14, 2, 16, 46, 418, DateTimeKind.Utc).AddTicks(2146)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 14, 2, 16, 46, 418, DateTimeKind.Utc).AddTicks(2148),
                            Name = "Afternoon",
                            UpdatedAt = new DateTime(2024, 1, 14, 2, 16, 46, 418, DateTimeKind.Utc).AddTicks(2148)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 14, 2, 16, 46, 418, DateTimeKind.Utc).AddTicks(2149),
                            Name = "Evening",
                            UpdatedAt = new DateTime(2024, 1, 14, 2, 16, 46, 418, DateTimeKind.Utc).AddTicks(2149)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 14, 2, 16, 46, 418, DateTimeKind.Utc).AddTicks(2150),
                            Name = "Anytime",
                            UpdatedAt = new DateTime(2024, 1, 14, 2, 16, 46, 418, DateTimeKind.Utc).AddTicks(2150)
                        });
                });

            modelBuilder.Entity("DailyRhythms.Models.DailyLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DailyLogs");
                });

            modelBuilder.Entity("DailyRhythms.Models.DailyLogToDoItem", b =>
                {
                    b.Property<int>("DailyLogId")
                        .HasColumnType("integer");

                    b.Property<int>("ToDoItemId")
                        .HasColumnType("integer");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.HasKey("DailyLogId", "ToDoItemId");

                    b.HasIndex("ToDoItemId");

                    b.ToTable("DailyLogToDoItems");
                });

            modelBuilder.Entity("DailyRhythms.Models.ToDoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DeletedAt")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("ToDoItems");
                });

            modelBuilder.Entity("DailyRhythms.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DailyRhythms.Models.DailyLog", b =>
                {
                    b.HasOne("DailyRhythms.Models.User", "User")
                        .WithMany("DailyLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DailyRhythms.Models.DailyLogToDoItem", b =>
                {
                    b.HasOne("DailyRhythms.Models.DailyLog", "DailyLog")
                        .WithMany("DailyLogToDoItems")
                        .HasForeignKey("DailyLogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DailyRhythms.Models.ToDoItem", "ToDoItem")
                        .WithMany("DailyLogToDoItems")
                        .HasForeignKey("ToDoItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DailyLog");

                    b.Navigation("ToDoItem");
                });

            modelBuilder.Entity("DailyRhythms.Models.ToDoItem", b =>
                {
                    b.HasOne("DailyRhythms.Models.Category", "Category")
                        .WithMany("ToDoItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DailyRhythms.Models.User", "User")
                        .WithMany("ToDoItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DailyRhythms.Models.Category", b =>
                {
                    b.Navigation("ToDoItems");
                });

            modelBuilder.Entity("DailyRhythms.Models.DailyLog", b =>
                {
                    b.Navigation("DailyLogToDoItems");
                });

            modelBuilder.Entity("DailyRhythms.Models.ToDoItem", b =>
                {
                    b.Navigation("DailyLogToDoItems");
                });

            modelBuilder.Entity("DailyRhythms.Models.User", b =>
                {
                    b.Navigation("DailyLogs");

                    b.Navigation("ToDoItems");
                });
#pragma warning restore 612, 618
        }
    }
}
