name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Setup .NET Core
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'  

      # Install Node.js for Angular build
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18' 

      # Build Angular app
      - name: Build Angular
        run: |
          cd client  
          npm install
          npm run build

      # Copy Angular build to .NET Core wwwroot
      - name: Copy Angular build to .NET Core wwwroot
        run: |
          cp -r client/dist/client/* DailyRhythms/wwwroot/

      # Build .NET Core app
      - name: Build .NET Core
        run: |
          cd DailyRhythms  
          dotnet publish -c Release -o out

      # Deploy to DigitalOcean
      - name: Deploy to DigitalOcean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DO_DROPLET_IP }}
          username: ${{ secrets.DO_DROPLET_USER }}
          password: ${{ secrets.DO_DROPLET_PASSWORD }}
          source: "DailyRhythms/out/*"
          target: "/var/DailyRhythms"

      # Restart .NET Core app
      - name: Restart .NET Core app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_DROPLET_IP }}
          username: ${{ secrets.DO_DROPLET_USER }}
          password: ${{ secrets.DO_DROPLET_PASSWORD }}
          script: |
            cd /var/DailyRhythms
            systemctl restart systemd-journald
            sudo systemctl start DailyRhythms-web.service
            
            
