name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Setup .NET Core
      
      # Restart .NET Core app
      - name: Clone Project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_DROPLET_IP }}
          username: ${{ secrets.DO_DROPLET_USER }}
          password: ${{ secrets.DO_DROPLET_PASSWORD }}
          port: 22
          script: |
            mkdir dailyrhythmclone 
            cd  dailyrhythmclone
            ls
            git clone git@github.com:Sital1/DailyRhythms.git
            echo 'Deployment successful to digital ocean' 
            
            
